name: vis24
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12.*
  - pip
  - pip:
    - ipykernel==6.29.*
    - numpy==2.0.*
    - pandas==2.2.*
    - scikit-learn==1.5.*
    - matplotlib==3.9.*
    - seaborn==0.13.*
    - bokeh==3.5.*
    - altair==5.3.*
    - plotly==5.22.*
    - streamlit==1.36.*
